sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_36d18748ef97_key -iv $encrypted_36d18748ef97_iv
  -in client-secret.json.enc -out client-secret.json -d
- docker build -t astianseb/docker-react -f Dockerfile.dev .
script:
- docker run -e CI=true astianseb/docker-react npm run test
deploy:
  provider: gae
  keyfile: client-secret.json.enc
  project: docker-react-2
  edge: true
  on:
    branch: master
